[2024-05-08T02:26:38.514+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-08T02:26:38.541+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_table_dump.mysql_table_dump_task manual__2024-05-08T02:26:36.303535+00:00 [queued]>
[2024-05-08T02:26:38.553+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_table_dump.mysql_table_dump_task manual__2024-05-08T02:26:36.303535+00:00 [queued]>
[2024-05-08T02:26:38.554+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-08T02:26:38.579+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): mysql_table_dump_task> on 2024-05-08 02:26:36.303535+00:00
[2024-05-08T02:26:38.586+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=119) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-08T02:26:38.588+0000] {standard_task_runner.py:63} INFO - Started process 120 to run task
[2024-05-08T02:26:38.588+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mysql_table_dump', 'mysql_table_dump_task', 'manual__2024-05-08T02:26:36.303535+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/dump_load_dag.py', '--cfg-path', '/tmp/tmpgqfa_zqf']
[2024-05-08T02:26:38.590+0000] {standard_task_runner.py:91} INFO - Job 111: Subtask mysql_table_dump_task
[2024-05-08T02:26:38.655+0000] {task_command.py:426} INFO - Running <TaskInstance: mysql_table_dump.mysql_table_dump_task manual__2024-05-08T02:26:36.303535+00:00 [running]> on host 19bc3fa20215
[2024-05-08T02:26:38.768+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mysql_table_dump' AIRFLOW_CTX_TASK_ID='mysql_table_dump_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-08T02:26:36.303535+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-08T02:26:36.303535+00:00'
[2024-05-08T02:26:38.770+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-08T02:26:38.804+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-08T02:26:38.805+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'mysqldump -u root -pmysql@123 -h host.docker.internal -P 3306 fc_facts facts > /opt/***/dags/dump_file.sql 2>/opt/***/dags/dump_error.log']
[2024-05-08T02:26:38.818+0000] {subprocess.py:86} INFO - Output:
[2024-05-08T02:26:39.221+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-08T02:26:39.222+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-08T02:26:39.246+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=mysql_table_dump, task_id=mysql_table_dump_task, execution_date=20240508T022636, start_date=20240508T022638, end_date=20240508T022639
[2024-05-08T02:26:39.283+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-08T02:26:39.313+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-08T02:26:39.316+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
